#!/bin/sh
#
# An example hook script to make use of push options.
# The example simply echoes all push options that start with 'echoback='
# and rejects all pushes when the "reject" push option is used.
#
# To enable this hook, rename this file to "pre-receive".

while read oldrev newrev refname
do
    AUTHOR=$(git rev-list --format=%an $newrev | tail -n1)
    if [[ $AUTHOR == "lms" ]]
    then
        echo 'reject lms push commit'
        exit 1
    fi
done
